### ISSUE TITLE
Баг с добавлением комментариев к полям, при использовании YAML

### ISSUE THREAD

**Issue by Lisovsky-UwU** [FosterToster/metaconfig#7]
Если описать вот такую конфигурацию
```python
from ..ext.parametrica.parametrica import Parametrica, Fieldset, Field, InRange, Min, Match
from ..ext.parametrica.parametrica.io import YAMLFileConfigIO
from ..ext.rk7_api import RKClientConnection, RKClientConfig


class Log(Fieldset):
    level = Field[int](3).label("Уровень логирования").rule(InRange(0, 10))
    retention_days = Field[int](7).label("Срок хранения .log файлов").rule(Min(1))


class Server(Fieldset):
    host = Field[str]("127.0.0.1").label("Хост")
    port = Field[int](8000).label("Порт")


class RKConnection(Fieldset, RKClientConnection, RKClientConfig):
    # Определим константные значения
    use_tcp = False
    use_saas = False

    # Определим динамические значения
    host = Field[str]('127.0.0.1')
    port = Field[int](3001)
    user = Field[str]('username')
    password = Field[str]('password')

    @property
    def connection(self):
        return self


class Config(Parametrica):
    log = Field[Log]().label("Параметры логирования")
    server = Field[Server]().label("Параметры сервера")
    rk_server = Field[RKConnection]().label("Параметры подключения к api RKeeper")


config = Config(YAMLFileConfigIO('r_keeper_api_settings.yaml'))
```

То при первом запуске конфиг приложения превращается что-то типо такого
```yaml
# Параметры логирования 
log:
  # Уровень логирования (int)
  level: 3
  # Срок хранения .log файлов (int)
  retention_days: 7
server:
  host: 127.0.0.1
  port: 8000
rk_# Параметры сервера 
server:
  # Хост (str)
  host: 127.0.0.1
  # Порт (int)
  port: 3001
  user: username
  password: password
```

Что уже является невалидным ямлом.
Проблема в функции `make_comments` класса `YAMLFileConfigIO`. Там реализовано через поиск полей уже в готовой строке YAML и дописание к этим полям комментариев. Работает поиск по регулярке, но эта регулярка, с приведенным выше примером, находит два соответствия `server`, берет последнее `rkeeper_server` и меняет часть поля
